name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Build release
        id: build
        run: |
          make release/aftershock.love

      - uses: actions/upload-artifact@v2
        with:
          name: aftershock.love
          path: release/aftershock.love
          retention-days: 1

  appimage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Build release
        id: build
        run: |
          make release/aftershock.AppImage

      - uses: actions/upload-artifact@v2
        with:
          name: aftershock.AppImage
          path: release/aftershock.AppImage
          retention-days: 1

  windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Build release
        id: build
        run: |
          make release/aftershock-win64.zip

      - uses: actions/upload-artifact@v2
        with:
          name: aftershock-win64.zip
          path: release/aftershock-win64.zip
          retention-days: 1

  osx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Build release
        id: build
        run: |
          make release/aftershock-osx.zip

      - uses: actions/upload-artifact@v2
        with:
          name: aftershock-osx.zip
          path: release/aftershock-osx.zip
          retention-days: 1


  create-release:
    needs: [linux, appimage, windows, osx]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - name: Set tag name
        run: |
          TAG_NAME=${{ github.ref }}
          echo "TAG_NAME=${TAG_NAME#refs/tags/}" >> $GITHUB_ENV

      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $TAG_NAME --target $GITHUB_SHA aftershock.love/* aftershock-win64.zip/* aftershock.AppImage/* aftershock-osx.zip/*

  publish:
    needs: [create-release]
    runs-on: ubuntu-latest

    env:
      BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
      ITCH_GAME: aftershock
      ITCH_USER: drhayes
      VERSION_FILE: version_file.txt

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - name: Set version
        run: |
          echo "${GITHUB_REF_NAME}" >> version_file.txt

      - name: Push win64
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          CHANNEL: win64
          PACKAGE: aftershock-win64.zip/aftershock-win64.zip

      - name: Push linux
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          CHANNEL: linux
          PACKAGE: aftershock.love/aftershock.love

      - name: Push linux-appimage
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          CHANNEL: linux-appimage
          PACKAGE: aftershock.AppImage/aftershock.AppImage

      - name: Push osx
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          CHANNEL: osx
          PACKAGE: aftershock-osx.zip/aftershock-osx.zip

